import React,{useEffect,useMemo,useState} from 'react';
import * as I from 'lucide-react';
import {api} from './api';

const NAV=[['dashboard','Command'],['monitor','Telemetry'],['ai','Intelligence'],['projects','Projects'],['files','Workspace'],['terminal','Terminal'],['astronomy','Astronomy'],['visual3d','Spatial Lab'],['automation','Automation'],['notifications','Inbox'],['analytics','Analytics'],['security','Security'],['settings','Settings'],['about','System']];
const ICON={dashboard:I.LayoutDashboard,monitor:I.Activity,ai:I.Sparkles,projects:I.Briefcase,files:I.FolderOpen,terminal:I.Terminal,astronomy:I.Orbit,visual3d:I.Box,automation:I.Workflow,notifications:I.Bell,analytics:I.ChartNoAxesCombined,security:I.ShieldCheck,settings:I.Settings,about:I.Cpu};
const PROJECTS=[{name:'FlyMind Lab',type:'Neural simulation',lang:'Python',progress:72,status:'ACTIVE',owner:'Research',risk:'LOW'},{name:'Aurora Core',type:'Interface platform',lang:'TypeScript',progress:91,status:'BUILDING',owner:'Platform',risk:'LOW'},{name:'Stellar Atlas',type:'Astronomy toolkit',lang:'React',progress:48,status:'PAUSED',owner:'Science',risk:'MEDIUM'},{name:'Atmospheric Lab',type:'Storm visualization',lang:'WebGL',progress:100,status:'COMPLETE',owner:'R&D',risk:'LOW'}];
const FILES=[['aurora-core','DIR','—'],['experiments','DIR','—'],['datasets','DIR','—'],['system-config.json','JSON','8.4 KB'],['neural-map.wlz','WLZ','24.7 MB'],['stellar-catalog.csv','CSV','4.2 MB'],['README.md','MD','12.1 KB'],['telemetry.schema.json','JSON','6.7 KB']];
const COMMANDS={help:'Available: help, status, metrics, projects, scan, ai, clear, version',status:'SYSTEM OPERATIONAL · 14 modules · 18 channels · local control plane',metrics:'Telemetry stream nominal · CPU/GPU/RAM/NET channels active',projects:'4 indexed projects · 1 complete · 1 active · 1 building · 1 paused',scan:'Workspace scan complete · 247 objects indexed · 0 integrity faults',ai:'Local intelligence adapter ready · external model: disconnected',version:'AURORA CONTROL CENTER 2.0 · LOCAL BUILD'};
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function Spark({values}){const min=Math.min(...values),max=Math.max(...values);const pts=values.map((v,i)=>`${i/(values.length-1)*100},${92-(v-min)/(max-min||1)*76}`).join(' ');return <svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts}/></svg>}
function Panel({title,kicker,children,action}){return <section className="panel"><div className="panel-head"><div><small>{kicker}</small><h3>{title}</h3></div>{action||<I.MoreHorizontal size={16}/>}</div>{children}</section>}
function Title({kicker,title,desc,children}){return <div className="title"><div><small>{kicker}</small><h1>{title}</h1><p>{desc}</p></div>{children}</div>}
function Metric({name,value,unit,delta,icon:Icon}){return <div className="metric"><div className="metric-icon"><Icon size={16}/></div><div className="metric-copy"><small>{name}</small><strong>{value}<em>{unit}</em></strong><span>{delta}</span></div></div>}

export default function App(){
 const [page,setPage]=useState('dashboard'),[collapsed,setCollapsed]=useState(false),[query,setQuery]=useState(''),[toast,setToast]=useState(null),[settings,setSettings]=useState(()=>JSON.parse(localStorage.getItem('aurora-settings')||'{"glow":65,"motion":true,"glass":true,"density":"comfortable"}'));
 const [metrics,setMetrics]=useState({cpu:36,gpu:44,ram:61,temp:54,network:184,uptime:0}),[history,setHistory]=useState(Array.from({length:42},(_,i)=>42+Math.sin(i/3)*7+(i%5)));
 const [chat,setChat]=useState([{role:'ai',text:'Intelligence console online. I can orchestrate local workspace functions, but no external model is connected.'}]),[input,setInput]=useState('');
 const [terminal,setTerminal]=useState(['AURORA SHELL 2.0','Secure local command plane initialized.','Type help to inspect available commands.']),[cmd,setCmd]=useState('');
 const [autos,setAutos]=useState([]),[notes,setNotes]=useState([{id:1,type:'success',title:'Telemetry online',text:'All local channels are responding normally.',time:'2m'},{id:2,type:'warning',title:'Archive threshold',text:'Workspace archive is nearing its configured threshold.',time:'22m'},{id:3,type:'info',title:'Core upgraded',text:'AURORA 2.0 control plane initialized.',time:'41m'}]);
 const notify=(text,type='info')=>{setToast({text,type});setTimeout(()=>setToast(null),2600)};
 useEffect(()=>{localStorage.setItem('aurora-settings',JSON.stringify(settings));document.documentElement.style.setProperty('--glow',settings.glow/100)},[settings]);
 useEffect(()=>{let alive=true;const tick=async()=>{const d=await api('/metrics');if(alive&&!d.offline){setMetrics(d);setHistory(h=>[...h.slice(1),d.cpu])}else{setMetrics(m=>({...m,cpu:clamp(m.cpu+(Math.random()-.5)*5,18,78),gpu:clamp(m.gpu+(Math.random()-.5)*6,18,86),ram:clamp(m.ram+(Math.random()-.5)*2,48,74),temp:clamp(m.temp+(Math.random()-.5)*2,47,68),network:Math.round(clamp(m.network+(Math.random()-.5)*22,90,320))}));}};tick();const id=setInterval(tick,1800);return()=>{alive=false;clearInterval(id)}},[]);
 useEffect(()=>{api('/automations').then(d=>!d.offline&&setAutos(d))},[]);
 const filtered=useMemo(()=>FILES.filter(f=>f[0].toLowerCase().includes(query.toLowerCase())),[query]);
 const send=()=>{const q=input.trim();if(!q)return;setChat(c=>[...c,{role:'user',text:q},{role:'ai',text:`Local orchestration received: “${q}”. No external model endpoint is configured, so this response remains a deterministic local acknowledgment.`}]);setInput('')};
 const run=()=>{const c=cmd.trim().toLowerCase();if(!c)return;if(c==='clear')setTerminal([]);else setTerminal(t=>[...t,`aurora@control:~$ ${cmd}`,COMMANDS[c]||`Unknown command: ${cmd}. Type help.`]);setCmd('')};
 const toggleAuto=async a=>{setAutos(x=>x.map(v=>v.id===a.id?{...v,active:!v.active}:v));const d=await api(`/automations/${a.id}`,{method:'PATCH',body:JSON.stringify({active:!a.active})});if(d.offline)notify('Backend offline. Change kept in local UI.','warning')};
 const render=()=>{switch(page){case'dashboard':return <Dashboard m={metrics} h={history} go={setPage} notes={notes}/>;case'monitor':return <Monitor m={metrics} h={history}/>;case'ai':return <AI chat={chat} input={input} setInput={setInput} send={send}/>;case'projects':return <Projects notify={notify}/>;case'files':return <Files files={filtered} query={query} setQuery={setQuery} notify={notify}/>;case'terminal':return <Terminal terminal={terminal} cmd={cmd} setCmd={setCmd} run={run}/>;case'astronomy':return <Astronomy/>;case'visual3d':return <Spatial/>;case'automation':return <Automation autos={autos} toggle={toggleAuto}/>;case'notifications':return <Inbox notes={notes} setNotes={setNotes}/>;case'analytics':return <Analytics h={history} m={metrics}/>;case'security':return <Security/>;case'settings':return <Settings settings={settings} setSettings={setSettings} notify={notify}/>;default:return <About/>}};
 return <div className={`app ${collapsed?'collapsed':''} ${settings.motion?'motion':''} ${settings.glass?'glass':''} density-${settings.density}`}><aside className="sidebar"><div className="brand"><div className="brandmark"><I.Aperture/></div><div><b>AURORA</b><small>CONTROL PLANE</small></div></div><div className="system-pill"><i/> <span>SYSTEM OPERATIONAL</span><em>2.0</em></div><nav>{NAV.map(([id,label])=>{const Icon=ICON[id];return <button className={page===id?'active':''} key={id} onClick={()=>setPage(id)} title={label}><Icon size={17}/><span>{label}</span>{id==='notifications'&&notes.length?<em>{notes.length}</em>:null}</button>})}</nav><div className="side-bottom"><div><span>INSTANCE</span><b>LOCAL-01</b></div><div><span>CHANNEL</span><b>SECURE</b></div></div></aside><main><header><div className="breadcrumb"><small>CORE /</small><b>{NAV.find(x=>x[0]===page)?.[1]}</b></div><div className="head-right"><div className="clock"><strong>{new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</strong><small>{new Date().toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}</small></div><button onClick={()=>notify('All telemetry channels nominal.')} aria-label="Connection"><I.Radio size={17}/></button><button onClick={()=>setPage('notifications')} aria-label="Notifications"><I.Bell size={17}/><i className="live-dot"/></button><button onClick={()=>setPage('settings')} aria-label="Settings"><I.Settings size={17}/></button><div className="avatar">A</div><button onClick={()=>setCollapsed(v=>!v)} aria-label="Collapse sidebar"><I.PanelLeft size={17}/></button></div></header><div className="content">{render()}</div></main>{toast&&<div className={`toast ${toast.type}`}><I.Activity size={16}/>{toast.text}</div>}</div>
}

function Dashboard({m,h,go,notes}){return <><div className="hero"><div><small>PRIMARY COMMAND / LIVE</small><h1>Command your workspace.</h1><p>A unified operational surface for computation, research, automation and intelligence.</p></div><div className="health"><div className="health-ring"><I.Activity/></div><span><b>OPERATIONAL</b><small>12ms median latency</small></span></div></div><div className="metrics"><Metric name="CPU" value={Math.round(m.cpu)} unit="%" delta="within baseline" icon={I.Cpu}/><Metric name="GPU" value={Math.round(m.gpu)} unit="%" delta="compute nominal" icon={I.Gpu}/><Metric name="MEMORY" value={Math.round(m.ram)} unit="%" delta="9.4 GB available" icon={I.MemoryStick}/><Metric name="THERMAL" value={Math.round(m.temp)} unit="°C" delta="stable" icon={I.Thermometer}/><Metric name="NETWORK" value={Math.round(m.network)} unit="Mbps" delta="secure link" icon={I.Wifi}/></div><div className="dash-grid"><Panel title="Live telemetry" kicker="STREAM / 42 SAMPLES" action={<span className="live-label"><i/>LIVE</span>}><div className="chart-main"><div><strong>{Math.round(m.cpu)}%</strong><span>CPU utilization</span></div><Spark values={h}/><div className="axis"><span>-30m</span><span>-20m</span><span>-10m</span><span>NOW</span></div></div></Panel><Panel title="Operational matrix" kicker="SERVICE HEALTH"><div className="service-list">{['Telemetry','Intelligence','Workspace','Automation','Science','Security'].map((x,i)=><div key={x}><i/><b>{x}</b><span>{i===1?'STANDBY':'NOMINAL'}</span></div>)}</div></Panel><Panel title="Project radar" kicker="ACTIVE WORK"><div className="radar-list">{PROJECTS.slice(0,3).map(p=><div key={p.name} onClick={()=>go('projects')}><span className="mini-icon"><I.Layers size={15}/></span><b>{p.name}<small>{p.type}</small></b><em>{p.progress}%</em></div>)}</div></Panel><Panel title="Event stream" kicker="LATEST EVENTS"><div className="events">{notes.map(n=><div key={n.id}><time>{n.time}</time><span><b>{n.title}</b><small>{n.text}</small></span></div>)}</div></Panel></div></>}
function Monitor({m,h}){return <><Title kicker="SYSTEM / TELEMETRY" title="Telemetry center" desc="Continuous resource observation with a backend-ready metric stream."/><div className="monitor-grid">{[['PROCESSOR',m.cpu,'%',I.Cpu],['GRAPHICS',m.gpu,'%',I.Gpu],['MEMORY',m.ram,'%',I.MemoryStick],['THERMAL',m.temp,'°C',I.Thermometer],['NETWORK',m.network,'Mbps',I.Wifi],['UPTIME',Math.floor(m.uptime/60),'min',I.Clock3]].map(([n,v,u,Icon])=><Panel key={n} title={n} kicker="LIVE CHANNEL"><div className="reading"><Icon size={17}/><strong>{Math.round(v)}<em>{u}</em></strong><div className="bar"><i style={{width:`${n==='NETWORK'?Math.min(v/3.2,100):Math.min(v,100)}%`}}/></div><Spark values={h}/><small>STATUS · <b>NOMINAL</b></small></div></Panel>)}</div></>}
function AI({chat,input,setInput,send}){return <><Title kicker="INTELLIGENCE / ORCHESTRATION" title="Intelligence console" desc="Prepared for a real local model adapter. No external inference is falsely represented."/><div className="ai-layout"><aside className="ai-side"><div className="orb"><I.Sparkles/></div><b>AURORA INTELLIGENCE</b><small>LOCAL ADAPTER</small><div className="ai-status"><i/>READY</div><div className="ctx"><span>CONTEXT WINDOW</span><b>8.2K / 16K</b><div className="bar"><i style={{width:'51%'}}/></div></div>{['Analyze telemetry','Summarize projects','Inspect workspace','Explain architecture'].map(x=><button key={x} onClick={()=>setInput(x)}>{x}<I.ChevronRight size={13}/></button>)}</aside><section className="chat"><div className="chatbar"><span>SESSION / 001</span><small>LOCAL · DETERMINISTIC FALLBACK</small></div><div className="messages">{chat.map((x,i)=><div className={`message ${x.role}`} key={i}><div className="msg-avatar">{x.role==='ai'?'A':'U'}</div><div><small>{x.role==='ai'?'AURORA':'OPERATOR'}</small><p>{x.text}</p></div></div>)}</div><div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Issue an instruction..."/><button aria-label="Attach"><I.Paperclip size={16}/></button><button className="send" onClick={send}><I.ArrowUp size={17}/></button></div></section></div></>}
function Files({files,query,setQuery,notify}){return <><Title kicker="WORKSPACE / DATA" title="Workspace explorer" desc="Structured project data with a clean adapter boundary for real filesystem integration."/><div className="files"><aside><small>WORKSPACE TREE</small>{['AURORA CORE','EXPERIMENTS','DATASETS','ARCHIVE'].map((x,i)=><div className={i===0?'selected':''} key={x}><I.Folder size={15}/><span>{x}</span><em>{[8,12,4,21][i]}</em></div>)}</aside><section><div className="filebar"><span>ROOT / AURORA</span><label><I.Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter indexed objects"/></label></div><div className="filehead"><span>OBJECT</span><span>TYPE</span><span>SIZE</span></div>{files.map(f=><button className="filerow" key={f[0]} onClick={()=>notify(`${f[0]} selected`)}><I.FileCode size={16}/><b>{f[0]}</b><span>{f[1]}</span><em>{f[2]}</em></button>)}</section></div></>}
function Terminal({terminal,cmd,setCmd,run}){return <><Title kicker="SYSTEM / COMMAND PLANE" title="Terminal" desc="Sandboxed command interpreter. It never executes arbitrary host commands."/><div className="terminal"><div className="termbar"><span><i/>AURORA SHELL</span><small>SAFE MODE / LOCAL</small></div><div className="termout">{terminal.map((x,i)=><div key={i} className={x.startsWith('Unknown')?'err':''}>{x}</div>)}<div className="prompt"><b>aurora@control:~$</b><input autoFocus value={cmd} onChange={e=>setCmd(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()}/></div></div></div></>}
function Projects({notify}){return <><Title kicker="PORTFOLIO / DELIVERY" title="Project command" desc="Lifecycle, ownership and delivery posture across the workspace."/><div className="project-grid">{PROJECTS.map(p=><article className="project"><div className="project-top"><span className="project-symbol"><I.Layers size={18}/></span><span className={`status ${p.status.toLowerCase()}`}>{p.status}</span></div><h3>{p.name}</h3><p>{p.type}</p><div className="project-info"><span>OWNER <b>{p.owner}</b></span><span>RISK <b>{p.risk}</b></span></div><div className="progress"><i style={{width:`${p.progress}%`}}/></div><div className="project-bottom"><b>{p.progress}%</b><button onClick={()=>notify(`${p.name} opened in workspace`)}>OPEN <I.ArrowUpRight size={14}/></button></div></article>)}</div></>}
function Astronomy(){return <><Title kicker="SCIENCE / CELESTIAL" title="Astronomy lab" desc="A local scientific visualization surface using representative data."/><div className="science-grid"><Panel title="Observation sphere" kicker="EARTH / FOCUS"><div className="planet"><div className="planet-core"/><div className="orbit one"/><div className="orbit two"/><div className="planet-grid"/></div></Panel><Panel title="Observation telemetry" kicker="SIMULATED DATA"><div className="science"><div><span>ALTITUDE</span><b>408.2 km</b></div><div><span>VELOCITY</span><b>7.66 km/s</b></div><div><span>MAGNITUDE</span><b>-3.74</b></div><div><span>ILLUMINATION</span><b>84.1%</b></div><div><span>REFERENCE</span><b>LEO / LOCAL</b></div></div></Panel></div></>}
function Spatial(){const [rot,setRot]=useState(18),[zoom,setZoom]=useState(1);return <><Title kicker="SCIENCE / SPATIAL ENGINE" title="Spatial lab" desc="Interactive CSS scene with selection, rotation and zoom controls."/><div className="spatial"><aside><span>SCENE CONTROL</span><label>ROTATION <b>{rot}°</b></label><input type="range" min="0" max="360" value={rot} onChange={e=>setRot(+e.target.value)}/><label>ZOOM <b>{zoom.toFixed(1)}x</b></label><input type="range" min=".6" max="1.8" step=".1" value={zoom} onChange={e=>setZoom(+e.target.value)}/><button onClick={()=>{setRot(18);setZoom(1)}}>RESET VIEW</button></aside><div className="scene"><div className="cube" style={{transform:`scale(${zoom}) rotateX(58deg) rotateZ(${rot}deg)`}}><i/><i/><i/><i/></div><span className="coords">X +014.2 · Y -008.7 · Z +031.4</span></div></div></>}
function Automation({autos,toggle}){return <><Title kicker="OPERATIONS / ORCHESTRATION" title="Automation control" desc="Scheduled routines with explicit state and backend synchronization."/><div className="auto-grid">{autos.length?autos.map(a=><article className="automation"><div className="auto-icon"><I.Workflow size={18}/></div><div><h3>{a.name}</h3><p>Schedule · {a.schedule}</p><small>{a.runs} executions recorded</small></div><button className={a.active?'on':''} onClick={()=>toggle(a)}><i/></button></article>):<Panel title="Waiting for API" kicker="OFFLINE"><p className="empty">Start the local API to synchronize automation state.</p></Panel>}</div></>}
function Inbox({notes,setNotes}){return <><Title kicker="COMMUNICATION / EVENTS" title="Notification center" desc="Operational events, warnings and system acknowledgments." children={<button className="outline" onClick={()=>setNotes([])}>CLEAR ALL</button>}/><div className="inbox">{notes.map(n=><article key={n.id} className={n.type}><div><I.Bell size={16}/></div><span><b>{n.title}</b><p>{n.text}</p><small>{n.time}</small></span></article>)}</div>{!notes.length&&<Panel title="No active notifications" kicker="INBOX CLEAR"><p className="empty">The event queue is clear.</p></Panel>}</>}
function Analytics({h,m}){return <><Title kicker="OBSERVABILITY / ANALYTICS" title="Performance intelligence" desc="Derived views over the same live telemetry stream."/><div className="analytics"><Panel title="CPU trend" kicker="42 SAMPLES"><div className="analytic-chart"><Spark values={h}/></div></Panel><Panel title="Current profile" kicker="LIVE"><div className="profile"><div><span>CPU</span><b>{Math.round(m.cpu)}%</b></div><div><span>GPU</span><b>{Math.round(m.gpu)}%</b></div><div><span>RAM</span><b>{Math.round(m.ram)}%</b></div><div><span>THERMAL</span><b>{Math.round(m.temp)}°C</b></div></div></Panel></div></>}
function Security(){return <><Title kicker="SECURITY / TRUST" title="Security posture" desc="Local application controls and integration boundaries."/><div className="security-grid">{[['LOCAL DATA','Encrypted boundary','PASS',I.LockKeyhole],['API SURFACE','Explicit routes only','PASS',I.Route],['COMMAND PLANE','Sandboxed interpreter','PASS',I.Terminal],['EXTERNAL AI','No endpoint configured','ISOLATED',I.ShieldOff]].map(([a,b,c,Icon])=><Panel title={a} kicker="CONTROL"><div className="security-item"><Icon size={20}/><span>{b}</span><b>{c}</b></div></Panel>)}</div></>}
function Settings({settings,setSettings,notify}){const update=(k,v)=>setSettings(s=>({...s,[k]:v}));return <><Title kicker="CONTROL / PREFERENCES" title="System settings" desc="Tune the interface without pretending these switches control hardware they cannot reach."/><div className="settings-grid"><Panel title="Visual system" kicker="APPEARANCE"><div className="setting"><span>Glow intensity<small>Interface luminance</small></span><input type="range" min="0" max="100" value={settings.glow} onChange={e=>update('glow',+e.target.value)}/><b>{settings.glow}%</b></div><div className="setting"><span>Motion<small>Micro-interactions</small></span><button className={`switch ${settings.motion?'on':''}`} onClick={()=>update('motion',!settings.motion)}><i/></button></div><div className="setting"><span>Glass surfaces<small>Backdrop transparency</small></span><button className={`switch ${settings.glass?'on':''}`} onClick={()=>update('glass',!settings.glass)}><i/></button></div><div className="setting"><span>Density<small>Workspace spacing</small></span><select value={settings.density} onChange={e=>update('density',e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></div></Panel><Panel title="Runtime" kicker="INSTANCE"><div className="runtime"><span>BUILD <b>2.0.0</b></span><span>MODE <b>LOCAL</b></span><span>API <b>OPTIONAL</b></span></div><button className="outline" onClick={()=>notify('Preferences persisted locally.','success')}>SAVE PREFERENCES</button></Panel></div></>}
function About(){return <><Title kicker="CORE / ARCHITECTURE" title="About AURORA" desc="A modular local control plane designed to grow from simulation into real integrations."/><div className="about"><div className="about-logo"><I.Aperture size={42}/></div><h2>AURORA 2.0</h2><p>Command surface · telemetry · intelligence · workspace · science · automation.</p><div className="about-grid"><span>FRONTEND <b>React + Vite</b></span><span>STATE <b>Local + API</b></span><span>BACKEND <b>Node HTTP</b></span><span>SAFETY <b>Sandboxed</b></span></div></div></>}
