import React, {useEffect, useMemo, useState} from 'react';
import * as I from 'lucide-react';
import {modules, projects, files, automations, notifications, commandHelp} from './data';

const iconMap={dashboard:I.LayoutDashboard,monitor:I.Activity,ai:I.Sparkles,files:I.FolderOpen,terminal:I.Terminal,projects:I.Briefcase,astronomy:I.Orbit,visual3d:I.Box,automation:I.Workflow,notifications:I.Bell,settings:I.Settings,about:I.Info};
const labels={active:'Active',development:'Development',paused:'Paused',complete:'Complete'};
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));

function Metric({label,value,unit='',tone=''}){return <div className="metric"><div className="metric-head"><span>{label}</span><small>{unit}</small></div><strong className={tone}>{value}</strong></div>}
function Spark({data}){let max=Math.max(...data), min=Math.min(...data); let pts=data.map((v,i)=>`${(i/(data.length-1))*100},${100-((v-min)/(max-min||1))*78-11}`).join(' ');return <svg className="spark" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts}/></svg>}
function Panel({title,tag,children,wide=false}){return <section className={`panel ${wide?'wide':''}`}><div className="panel-title"><div><span className="eyebrow">{tag}</span><h3>{title}</h3></div><I.MoreHorizontal size={16}/></div>{children}</section>}

export default function App(){
 const [page,setPage]=useState('dashboard'); const [collapsed,setCollapsed]=useState(false); const [query,setQuery]=useState(''); const [toast,setToast]=useState(null);
 const [theme,setTheme]=useState('cyan'); const [glow,setGlow]=useState(70); const [motion,setMotion]=useState(true); const [transparency,setTransparency]=useState(true);
 const [stats,setStats]=useState({cpu:37,gpu:42,ram:61,temp:54,net:184}); const [history,setHistory]=useState(Array.from({length:28},(_,i)=>42+Math.sin(i/2)*7+i%4));
 const [chat,setChat]=useState([{role:'ai',text:'AURORA intelligence console ready. This workspace is operating in local simulation mode.'}]); const [input,setInput]=useState('');
 const [cmd,setCmd]=useState(''); const [terminal,setTerminal]=useState(['AURORA TERMINAL v1.0','Secure local simulation initialized.','Type “help” for available commands.']);
 const [auto,setAuto]=useState(automations); const [notes,setNotes]=useState(notifications);
 useEffect(()=>{const t=setInterval(()=>{setStats(s=>({cpu:clamp(s.cpu+(Math.random()-.5)*4,18,73),gpu:clamp(s.gpu+(Math.random()-.5)*5,15,81),ram:clamp(s.ram+(Math.random()-.5)*1.5,48,74),temp:clamp(s.temp+(Math.random()-.5)*1.2,47,68),net:Math.round(clamp(s.net+(Math.random()-.5)*18,90,310))}));setHistory(h=>[...h.slice(1),stats.cpu]);},1800);return()=>clearInterval(t)},[stats.cpu]);
 const now=new Date(); const time=now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}); const date=now.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});
 const current=modules.find(m=>m[0]===page)?.[1]||'Dashboard';
 const notify=(text,type='info')=>{setToast({text,type});setTimeout(()=>setToast(null),2800)};
 const sendChat=()=>{if(!input.trim())return;let q=input.trim();setChat(c=>[...c,{role:'user',text:q},{role:'ai',text:`Local analysis complete. I can interpret “${q}”, but no external model endpoint is configured in this build.`}]);setInput('')};
 const runCmd=()=>{let c=cmd.trim().toLowerCase();if(!c)return;if(c==='clear'){setTerminal([])}else setTerminal(t=>[...t,`aurora@local:~$ ${cmd}`,commandHelp[c]||`Command not recognized: ${cmd}. Type “help”.`]);setCmd('')};
 const filteredFiles=useMemo(()=>files.filter(f=>f.name.toLowerCase().includes(query.toLowerCase())),[query]);
 const toggleAuto=i=>setAuto(a=>a.map((x,n)=>n===i?{...x,active:!x.active}:x));
 const render=()=>{
  if(page==='dashboard')return <Dashboard stats={stats} history={history} projects={projects} setPage={setPage} />;
  if(page==='monitor')return <Monitor stats={stats} history={history}/>;
  if(page==='ai')return <AI chat={chat} input={input} setInput={setInput} sendChat={sendChat}/>;
  if(page==='files')return <Files query={query} setQuery={setQuery} files={filteredFiles} notify={notify}/>;
  if(page==='terminal')return <Terminal cmd={cmd} setCmd={setCmd} runCmd={runCmd} terminal={terminal}/>;
  if(page==='projects')return <Projects notify={notify}/>;
  if(page==='astronomy')return <Astronomy/>;
  if(page==='visual3d')return <Visual3D/>;
  if(page==='automation')return <Automation auto={auto} toggleAuto={toggleAuto}/>;
  if(page==='notifications')return <Notifications notes={notes} setNotes={setNotes}/>;
  if(page==='settings')return <Settings theme={theme} setTheme={setTheme} glow={glow} setGlow={setGlow} motion={motion} setMotion={setMotion} transparency={transparency} setTransparency={setTransparency}/>;
  return <About/>;
 };
 return <div className={`app ${collapsed?'is-collapsed':''} theme-${theme} ${motion?'motion-on':'motion-off'} ${transparency?'glass-on':''}`} style={{'--glow':`${glow/100}`}}>
  <aside className="sidebar"><div className="brand"><div className="brand-mark"><I.Aperture/></div><div className="brand-copy"><b>AURORA</b><span>CONTROL CENTER</span></div></div><div className="online"><i/>SYSTEM ONLINE</div><nav>{modules.map(([id,name])=>{let Icon=iconMap[id];return <button key={id} className={page===id?'active':''} onClick={()=>setPage(id)} aria-label={name} title={name}><Icon size={18}/><span>{name}</span>{id==='notifications'&&notes.length>0&&<em>{notes.length}</em>}</button>})}</nav><div className="side-footer"><span>LOCAL INSTANCE</span><strong>v1.0.0</strong><small>SECURE CHANNEL · 01</small></div></aside>
  <main><header><div className="crumb"><span>CORE /</span><b>{current}</b></div><div className="header-actions"><div className="header-clock"><strong>{time}</strong><small>{date}</small></div><button onClick={()=>notify('All telemetry channels are nominal.')} aria-label="System status"><I.Wifi size={17}/></button><button onClick={()=>setPage('notifications')} aria-label="Notifications"><I.Bell size={17}/><i className="dot"/></button><button onClick={()=>setPage('settings')} aria-label="Settings"><I.Settings size={17}/></button><div className="avatar">A</div><button className="collapse" onClick={()=>setCollapsed(!collapsed)} aria-label="Toggle sidebar"><I.PanelLeft size={17}/></button></div></header><div className="content">{render()}</div></main>
  {toast&&<div className={`toast ${toast.type}`}><I.Activity size={17}/><span>{toast.text}</span></div>}
 </div>
}

function Dashboard({stats,history,projects,setPage}){return <><div className="hero"><div><span className="eyebrow">AURORA / PRIMARY CONSOLE</span><h1>Good evening, <span>operator.</span></h1><p>All systems are synchronized. Your control environment is stable and ready.</p></div><div className="hero-status"><div className="pulse-ring"><I.Activity size={22}/></div><span><b>OPERATIONAL</b><small>LATENCY 12ms</small></span></div></div><div className="metric-grid"><Metric label="CPU LOAD" value={`${Math.round(stats.cpu)}%`} unit="PROCESSOR"/><Metric label="GPU LOAD" value={`${Math.round(stats.gpu)}%`} unit="GRAPHICS"/><Metric label="MEMORY" value={`${Math.round(stats.ram)}%`} unit="RAM"/><Metric label="CORE TEMP" value={`${Math.round(stats.temp)}°`} unit="CELSIUS"/><Metric label="NETWORK" value={`${stats.net}`} unit="MBPS" tone="accent"/></div><div className="dashboard-grid"><Panel title="System activity" tag="LIVE TELEMETRY" wide><div className="chart-wrap"><div className="chart-labels"><b>{Math.round(stats.cpu)}%</b><span>CPU utilization · 30 samples</span></div><Spark data={history}/><div className="chart-axis"><span>-30m</span><span>-20m</span><span>-10m</span><span>NOW</span></div></div></Panel><Panel title="Module status" tag="12 SERVICES"><div className="status-list">{modules.slice(0,6).map(([id,n])=><div key={id}><span className="module-dot"/><b>{n}</b><small>READY</small></div>)}</div></Panel><Panel title="Recent projects" tag="WORKSPACE"><div className="project-list">{projects.slice(0,3).map(p=><div key={p.name} onClick={()=>setPage('projects')}><div className="project-icon"><I.Box size={16}/></div><span><b>{p.name}</b><small>{p.type} · {p.updated}</small></span><strong>{p.progress}%</strong></div>)}</div></Panel><Panel title="Event stream" tag="LIVE"><div className="event-list"><div><span>22:14:03</span><b>Telemetry heartbeat received</b></div><div><span>22:13:42</span><b>Workspace index synchronized</b></div><div><span>22:12:19</span><b>Archive threshold evaluated</b></div><div><span>22:11:57</span><b>Local intelligence console ready</b></div></div></Panel></div></>}

function Monitor({stats,history}){return <><PageTitle eyebrow="SYSTEM / TELEMETRY" title="System monitor" desc="Continuous local telemetry with coherent simulated readings."/><div className="monitor-grid">{[['CPU',stats.cpu,'%'],['GPU',stats.gpu,'%'],['RAM',stats.ram,'%'],['TEMP',stats.temp,'°C'],['NETWORK',stats.net,'Mbps']].map(([n,v,u])=><Panel key={n} title={n} tag="LIVE"><div className="big-reading"><strong>{Math.round(v)}<small>{u}</small></strong><div className="meter"><i style={{width:`${n==='NETWORK'?Math.min(v/3,100):v}%`}}/></div><Spark data={history.map((x,i)=>x+(i%5-2))}/><div className="reading-meta"><span>STATUS <b>NOMINAL</b></span><span>UPDATED 1.8s</span></div></div></Panel>)}</div><Panel title="Resource timeline" tag="HISTORICAL"><div className="timeline-chart"><Spark data={history.concat(history.map(x=>x+8))}/><div><span>30 MIN AGO</span><span>NOW</span></div></div></Panel></>}
function AI({chat,input,setInput,sendChat}){return <><PageTitle eyebrow="INTELLIGENCE / LOCAL" title="AI console" desc="A prepared conversational interface. No external model is claimed or connected."/><div className="ai-shell"><aside><div className="ai-model"><div className="ai-orb"><I.Sparkles/></div><b>AURORA LOCAL</b><small>SIMULATION ENGINE</small></div><div className="ai-state"><span className="module-dot"/>READY</div><div className="context"><span>CONTEXT</span><b>8.2K / 16K</b><div className="meter"><i style={{width:'51%'}}/></div></div><div className="chips"><button>Analyze system</button><button>Summarize workspace</button><button>Explain telemetry</button></div></aside><section className="chat"><div className="chat-top"><span>CONVERSATION / 001</span><small>PROCESSING MODE · LOCAL</small></div><div className="messages">{chat.map((m,i)=><div key={i} className={`msg ${m.role}`}><div className="msg-avatar">{m.role==='ai'?'A':'U'}</div><div><small>{m.role==='ai'?'AURORA':'OPERATOR'} · {i+1}</small><p>{m.text}</p></div></div>)}</div><div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder="Enter an instruction..."/><button aria-label="Attach"><I.Paperclip size={17}/></button><button className="send" onClick={sendChat} aria-label="Send"><I.ArrowUp size={18}/></button></div></section></div></>}
function Files({query,setQuery,files,notify}){return <><PageTitle eyebrow="DATA / WORKSPACE" title="File explorer" desc="A structured local workspace simulation, ready for a future filesystem adapter."/><div className="files-shell"><aside><div className="tree-title">WORKSPACE</div>{['AURORA','experiments','datasets','archive'].map((x,i)=><div className={`tree-row ${i===0?'selected':''}`} key={x}><I.Folder size={15}/><span>{x}</span>{i<3&&<small>{[7,12,4][i]}</small>}</div>)}</aside><section><div className="file-toolbar"><div className="path"><I.ChevronRight size={14}/>AURORA / WORKSPACE</div><div className="search"><I.Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter files"/></div></div><div className="file-head"><span>NAME</span><span>TYPE</span><span>SIZE</span></div>{files.map(f=><div className="file-row" key={f.name} onClick={()=>notify(`${f.name} selected`) }><I.FileCode size={17}/><b>{f.name}</b><span>{f.kind.toUpperCase()}</span><small>{f.size}</small></div>)}</section></div></>}
function Terminal({cmd,setCmd,runCmd,terminal}){return <><PageTitle eyebrow="SYSTEM / SHELL" title="Terminal" desc="Command simulation only. Nothing here executes against the host machine."/><div className="terminal"><div className="terminal-bar"><span><i/>AURORA SHELL</span><small>LOCAL / SANDBOXED</small></div><div className="terminal-body">{terminal.map((l,i)=><div key={i} className={l.includes('not recognized')?'err':''}>{l}</div>)}<div className="prompt"><span>aurora@local:~$</span><input autoFocus value={cmd} onChange={e=>setCmd(e.target.value)} onKeyDown={e=>e.key==='Enter'&&runCmd()} aria-label="Terminal command"/></div></div></div></>}
function Projects({notify}){return <><PageTitle eyebrow="WORKSPACE / PROJECTS" title="Project registry" desc="Indexed initiatives and their current lifecycle state."/><div className="project-grid">{projects.map(p=><article className="project-card" key={p.name}><div className="project-card-top"><div className="project-icon"><I.Layers size={18}/></div><span className={`badge ${p.status}`}>{labels[p.status]}</span></div><h3>{p.name}</h3><p>{p.type}</p><div className="progress"><i style={{width:`${p.progress}%`}}/></div><div className="project-meta"><span>{p.lang}</span><b>{p.progress}%</b></div><button onClick={()=>notify(`${p.name} opened in workspace`)}>OPEN PROJECT <I.ArrowUpRight size={14}/></button></article>)}</div></>}
function Astronomy(){return <><PageTitle eyebrow="SCIENCE / CELESTIAL" title="Astronomy" desc="A scientific visualization layer populated with representative local data."/><div className="astro-grid"><Panel title="Earth · observation focus" tag="OBJECT 001"><div className="planet"><div className="planet-glow"/><div className="planet-sphere"><span/><i/><b/></div><div className="orbit orbit-a"/><div className="orbit orbit-b"/></div></Panel><Panel title="Object telemetry" tag="SIMULATED DATA"><div className="science-list"><div><span>ALTITUDE</span><b>408.2 km</b></div><div><span>MAGNITUDE</span><b>-3.74</b></div><div><span>VELOCITY</span><b>7.66 km/s</b></div><div><span>ILLUMINATION</span><b>84.1%</b></div><div><span>OBSERVATION</span><b>NOMINAL</b></div></div></Panel><Panel title="Sky events" tag="NEXT 24 HOURS"><div className="event-list"><div><span>21:48</span><b>Jupiter · high visibility</b></div><div><span>23:16</span><b>Orionid candidate window</b></div><div><span>02:04</span><b>Lunar transit marker</b></div></div></Panel></div></>}
function Visual3D(){const [rot,setRot]=useState(20);return <><PageTitle eyebrow="LAB / SPATIAL" title="3D visualization" desc="Interactive CSS scene standing in for a future WebGL renderer."/><div className="viz-shell"><div className="viz-stage"><div className="grid-floor"/><div className="wire-cube" style={{transform:`rotateX(${rot/2}deg) rotateY(${rot}deg) rotateZ(${rot/4}deg)`}}><span/><span/><span/><span/><span/><span/></div><div className="viz-axis"><b>X</b><b>Y</b><b>Z</b></div></div><aside className="viz-controls"><span className="eyebrow">SCENE / 001</span><h3>Neural lattice</h3><p>Spatial placeholder with transform controls and selection metadata.</p><label>ROTATION <b>{rot}°</b><input type="range" min="0" max="360" value={rot} onChange={e=>setRot(+e.target.value)}/></label><div className="science-list"><div><span>OBJECTS</span><b>128</b></div><div><span>VERTICES</span><b>4,096</b></div><div><span>RENDER</span><b>CSS / LOCAL</b></div></div></aside></div></>}
function Automation({auto,toggleAuto}){return <><PageTitle eyebrow="ORCHESTRATION / LOCAL" title="Automations" desc="Scheduled workflows represented locally. No external jobs are triggered."/><div className="automation-list">{auto.map((a,i)=><div className="automation-row" key={a.name}><div className="auto-icon"><I.Workflow size={18}/></div><div className="auto-main"><b>{a.name}</b><span>{a.schedule}</span></div><div><small>NEXT</small><strong>{a.next}</strong></div><button className={`switch ${a.active?'on':''}`} onClick={()=>toggleAuto(i)} aria-label={`Toggle ${a.name}`}><i/></button></div>)}</div></>}
function Notifications({notes,setNotes}){return <><PageTitle eyebrow="SYSTEM / EVENTS" title="Notifications" desc="System messages and local event history."/><div className="notifications">{notes.map((n,i)=><div className={`notification ${n.type}`} key={i}><div className="note-icon">{n.type==='success'?<I.CheckCircle/>:n.type==='warning'?<I.TriangleAlert/>:n.type==='error'?<I.XCircle/>:<I.Info/>}</div><div><b>{n.title}</b><p>{n.text}</p><small>{n.time}</small></div><button onClick={()=>setNotes(x=>x.filter((_,j)=>j!==i))} aria-label="Dismiss"><I.X size={16}/></button></div>)}</div></>}
function Settings({theme,setTheme,glow,setGlow,motion,setMotion,transparency,setTransparency}){return <><PageTitle eyebrow="CORE / PREFERENCES" title="Settings" desc="Tune the presentation layer. Changes apply immediately."/><div className="settings-grid"><Panel title="Appearance" tag="VISUAL"><SettingRow label="Accent spectrum" desc="Choose the primary signal color"><div className="swatches">{['cyan','blue','violet'].map(x=><button key={x} className={`${x} ${theme===x?'selected':''}`} onClick={()=>setTheme(x)} aria-label={x}/>)}</div></SettingRow><SettingRow label="Glow intensity" desc="Controls luminous accents"><input className="range" type="range" min="0" max="100" value={glow} onChange={e=>setGlow(+e.target.value)}/></SettingRow><SettingRow label="Motion" desc="Respect reduced-motion preferences"><button className={`switch ${motion?'on':''}`} onClick={()=>setMotion(!motion)}><i/></button></SettingRow><SettingRow label="Glass surfaces" desc="Moderate panel transparency"><button className={`switch ${transparency?'on':''}`} onClick={()=>setTransparency(!transparency)}><i/></button></SettingRow></Panel><Panel title="AI defaults" tag="LOCAL MODEL"><div className="settings-static"><div><span>MODEL</span><b>AURORA LOCAL SIM</b></div><div><span>CONTEXT</span><b>16,384 TOKENS</b></div><div><span>REASONING</span><b>STANDARD</b></div><div><span>TEMPERATURE</span><b>0.70</b></div></div></Panel><Panel title="System" tag="INSTANCE"><div className="settings-static"><div><span>VERSION</span><b>1.0.0</b></div><div><span>ENVIRONMENT</span><b>LOCAL WEB</b></div><div><span>TELEMETRY</span><b>SIMULATED</b></div><div><span>BACKEND</span><b>NOT CONNECTED</b></div></div></Panel></div></>}
function SettingRow({label,desc,children}){return <div className="setting-row"><span><b>{label}</b><small>{desc}</small></span>{children}</div>}
function About(){return <div className="about"><div className="about-mark"><I.Aperture size={52}/></div><span className="eyebrow">AURORA / SYSTEM IDENTITY</span><h1>A control center built to feel alive.</h1><p>AURORA is a modular React interface for experimenting with futuristic software architecture, telemetry visualization, scientific tools and local AI workflows.</p><div className="about-stats"><div><b>12</b><span>MODULES</span></div><div><b>100%</b><span>LOCAL UI</span></div><div><b>0</b><span>FAKE BACKENDS</span></div></div></div>}
function PageTitle({eyebrow,title,desc}){return <div className="page-title"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>}
